### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by LKonijn** [sebpiller/ha-luke-roberts-lampf#1]
I would love to control my lamp using Home Assistant. When I install your code using HACS and add :

```
lights:
  platform: lukeroberts-lampf
  mac: XX:XX:XX:XX:XX:XX
  name: Lamp Luke Roberts
```

to the configuration.yaml I get the following error when checking the config file:

_Component error: lights - Integration 'lights' not found._

What am I doing wrong?
